Clustered graph serialization
hyperskill/code-submissions-clustering pull request #21
Opened 2022-10-09 20:09 UTC by eartser

2022-10-10 11:01 UTC, nbirillo requested changes
Great!

2022-10-10 11:01 UTC, nbirillo commented on code-submissions-clustering-core/src/test/kotlin/org/jetbrains/research/code/submissions/clustering/SerializationTest.kt
> +            val clusterer = SubmissionsGraphHAC(3.0)
Please, add a const for 3

2022-10-19 07:40 UTC, eartser commented on code-submissions-clustering-core/src/main/kotlin/org/jetbrains/research/code/submissions/clustering/util/SerializationUtil.kt
> +// COPY
Oops, useless comment indeed, removed it.

2022-10-19 08:35 UTC, nbirillo approved these changes
Great!

2022-10-19 08:35 UTC, merged